import { TieredAchievement } from './types';
import { 
    PaperAirplaneIcon, 
    RouteIcon,
    AirportIcon,
    SeatIcon,
    TrophyIcon,
    GlobeAltIcon
} from './components/icons';

export const AIRPORT_COORDS: Record<string, { lat: number; lon: number; city: string; country: string; }> = {
  'AKL': { lat: -37.0082, lon: 174.7917, city: 'Auckland', country: 'New Zealand' },
  'AMS': { lat: 52.3105, lon: 4.7683, city: 'Amsterdam', country: 'Netherlands' },
  'ARN': { lat: 59.6519, lon: 17.9186, city: 'Stockholm', country: 'Sweden' },
  'ATH': { lat: 37.9364, lon: 23.9444, city: 'Athens', country: 'Greece' },
  'ATL': { lat: 33.6407, lon: -84.4277, city: 'Atlanta', country: 'USA' },
  'BKK': { lat: 13.6900, lon: 100.7501, city: 'Bangkok', country: 'Thailand' },
  'BOG': { lat: 4.7016, lon: -74.1469, city: 'Bogotá', country: 'Colombia' },
  'BOM': { lat: 19.0896, lon: 72.8656, city: 'Mumbai', country: 'India' },
  'BOS': { lat: 42.3656, lon: -71.0096, city: 'Boston', country: 'USA' },
  'CAI': { lat: 30.1219, lon: 31.4056, city: 'Cairo', country: 'Egypt' },
  'CDG': { lat: 49.0097, lon: 2.5479, city: 'Paris', country: 'France' },
  'CPH': { lat: 55.6179, lon: 12.6560, city: 'Copenhagen', country: 'Denmark' },
  'DEL': { lat: 28.5562, lon: 77.1000, city: 'Delhi', country: 'India' },
  'DEN': { lat: 39.8561, lon: -104.6737, city: 'Denver', country: 'USA' },
  'DFW': { lat: 32.8998, lon: -97.0403, city: 'Dallas', country: 'USA' },
  'DUB': { lat: 53.4264, lon: -6.2499, city: 'Dublin', country: 'Ireland' },
  'DXB': { lat: 25.2532, lon: 55.3657, city: 'Dubai', country: 'UAE' },
  'EZE': { lat: -34.8222, lon: -58.5358, city: 'Buenos Aires', country: 'Argentina' },
  'FCO': { lat: 41.8003, lon: 12.2388, city: 'Rome', country: 'Italy' },
  'FRA': { lat: 50.0379, lon: 8.5622, city: 'Frankfurt', country: 'Germany' },
  'GRU': { lat: -23.4356, lon: -46.4731, city: 'São Paulo', country: 'Brazil' },
  'HKG': { lat: 22.3080, lon: 113.9185, city: 'Hong Kong', country: 'China' },
  'HND': { lat: 35.5494, lon: 139.7798, city: 'Tokyo', country: 'Japan' },
  'IAD': { lat: 38.9531, lon: -77.4565, city: 'Washington D.C.', country: 'USA' },
  'ICN': { lat: 37.4692, lon: 126.4505, city: 'Seoul', country: 'South Korea' },
  'IST': { lat: 41.2753, lon: 28.7519, city: 'Istanbul', country: 'Turkey' },
  'JFK': { lat: 40.6413, lon: -73.7781, city: 'New York', country: 'USA' },
  'JNB': { lat: -26.1392, lon: 28.2460, city: 'Johannesburg', country: 'South Africa' },
  'KUL': { lat: 2.7456, lon: 101.7099, city: 'Kuala Lumpur', country: 'Malaysia' },
  'LAX': { lat: 33.9416, lon: -118.4085, city: 'Los Angeles', country: 'USA' },
  'LHR': { lat: 51.4700, lon: -0.4543, city: 'London', country: 'UK' },
  'LIM': { lat: -12.0219, lon: -77.1143, city: 'Lima', country: 'Peru' },
  'LOS': { lat: 6.5774, lon: 3.3211, city: 'Lagos', country: 'Nigeria' },
  'MAD': { lat: 40.4983, lon: -3.5676, city: 'Madrid', country: 'Spain' },
  'MCO': { lat: 28.4312, lon: -81.3081, city: 'Orlando', country: 'USA' },
  'MEX': { lat: 19.4363, lon: -99.0721, city: 'Mexico City', country: 'Mexico' },
  'MIA': { lat: 25.7959, lon: -80.2870, city: 'Miami', country: 'USA' },
  'NBO': { lat: -1.3192, lon: 36.9278, city: 'Nairobi', country: 'Kenya' },
  'NRT': { lat: 35.7720, lon: 140.3863, city: 'Tokyo', country: 'Japan' },
  'ORD': { lat: 41.9742, lon: -87.9073, city: 'Chicago', country: 'USA' },
  'PEK': { lat: 40.0799, lon: 116.6031, city: 'Beijing', country: 'China' },
  'PVG': { lat: 31.1434, lon: 121.8052, city: 'Shanghai', country: 'China' },
  'SCL': { lat: -33.3930, lon: -70.7858, city: 'Santiago', country: 'Chile' },
  'SEA': { lat: 47.4490, lon: -122.3093, city: 'Seattle', country: 'USA' },
  'SFO': { lat: 37.6213, lon: -122.3790, city: 'San Francisco', country: 'USA' },
  'SGN': { lat: 10.8188, lon: 106.6518, city: 'Ho Chi Minh City', country: 'Vietnam' },
  'SIN': { lat: 1.3644, lon: 103.9915, city: 'Singapore', country: 'Singapore' },
  'SYD': { lat: -33.9399, lon: 151.1753, city: 'Sydney', country: 'Australia' },
  'SYX': { lat: 18.3028, lon: 109.4123, city: 'Sanya', country: 'China' },
  'TPE': { lat: 25.0777, lon: 121.2328, city: 'Taipei', country: 'Taiwan' },
  'VIE': { lat: 48.1103, lon: 16.5697, city: 'Vienna', country: 'Austria' },
  'YVR': { lat: 49.1939, lon: -123.184, city: 'Vancouver', country: 'Canada' },
  'YYZ': { lat: 43.6777, lon: -79.6248, city: 'Toronto', country: 'Canada' },
  'ZRH': { lat: 47.4582, lon: 8.5555, city: 'Zurich', country: 'Switzerland' },
};

export const COUNTRY_COORDS: Record<string, { lat: number; lon: number; name: string; code: string }> = {
  'Argentina': { lat: -38.4161, lon: -63.6167, name: 'Argentina', code: 'AR' },
  'Australia': { lat: -25.2744, lon: 133.7751, name: 'Australia', code: 'AU' },
  'Austria': { lat: 47.5162, lon: 14.5501, name: 'Austria', code: 'AT' },
  'Brazil': { lat: -14.2350, lon: -51.9253, name: 'Brazil', code: 'BR' },
  'Canada': { lat: 56.1304, lon: -106.3468, name: 'Canada', code: 'CA' },
  'Chile': { lat: -35.6751, lon: -71.5430, name: 'Chile', code: 'CL' },
  'China': { lat: 35.8617, lon: 104.1954, name: 'China', code: 'CN' },
  'Colombia': { lat: 4.5709, lon: -74.2973, name: 'Colombia', code: 'CO' },
  'Denmark': { lat: 56.2639, lon: 9.5018, name: 'Denmark', code: 'DK' },
  'Egypt': { lat: 26.8206, lon: 30.8025, name: 'Egypt', code: 'EG' },
  'France': { lat: 46.2276, lon: 2.2137, name: 'France', code: 'FR' },
  'Germany': { lat: 51.1657, lon: 10.4515, name: 'Germany', code: 'DE' },
  'Greece': { lat: 39.0742, lon: 21.8243, name: 'Greece', code: 'GR' },
  'India': { lat: 20.5937, lon: 78.9629, name: 'India', code: 'IN' },
  'Ireland': { lat: 53.4129, lon: -8.2439, name: 'Ireland', code: 'IE' },
  'Italy': { lat: 41.8719, lon: 12.5674, name: 'Italy', code: 'IT' },
  'Japan': { lat: 36.2048, lon: 138.2529, name: 'Japan', code: 'JP' },
  'Kenya': { lat: -0.0236, lon: 37.9062, name: 'Kenya', code: 'KE' },
  'Malaysia': { lat: 4.2105, lon: 101.9758, name: 'Malaysia', code: 'MY' },
  'Mexico': { lat: 23.6345, lon: -102.5528, name: 'Mexico', code: 'MX' },
  'Netherlands': { lat: 52.1326, lon: 5.2913, name: 'Netherlands', code: 'NL' },
  'New Zealand': { lat: -40.9006, lon: 174.8860, name: 'New Zealand', code: 'NZ' },
  'Nigeria': { lat: 9.0820, lon: 8.6753, name: 'Nigeria', code: 'NG' },
  'Peru': { lat: -9.1900, lon: -75.0152, name: 'Peru', code: 'PE' },
  'Singapore': { lat: 1.3521, lon: 103.8198, name: 'Singapore', code: 'SG' },
  'South Africa': { lat: -30.5595, lon: 22.9375, name: 'South Africa', code: 'ZA' },
  'South Korea': { lat: 35.9078, lon: 127.7669, name: 'South Korea', code: 'KR' },
  'Spain': { lat: 40.4637, lon: -3.7492, name: 'Spain', code: 'ES' },
  'Sweden': { lat: 60.1282, lon: 18.6435, name: 'Sweden', code: 'SE' },
  'Switzerland': { lat: 46.8182, lon: 8.2275, name: 'Switzerland', code: 'CH' },
  'Taiwan': { lat: 23.6978, lon: 120.9605, name: 'Taiwan', code: 'TW' },
  'Thailand': { lat: 15.8700, lon: 100.9925, name: 'Thailand', code: 'TH' },
  'Turkey': { lat: 38.9637, lon: 35.2433, name: 'Turkey', code: 'TR' },
  'UAE': { lat: 23.4241, lon: 53.8478, name: 'United Arab Emirates', code: 'AE' },
  'UK': { lat: 55.3781, lon: -3.4360, name: 'United Kingdom', code: 'GB' },
  'USA': { lat: 39.8283, lon: -98.5795, name: 'United States', code: 'US' },
  'Vietnam': { lat: 14.0583, lon: 108.2772, name: 'Vietnam', code: 'VN' },
};

export const COUNTRY_TO_CONTINENT: Record<string, string> = {
  'Argentina': 'South America',
  'Australia': 'Australia',
  'Austria': 'Europe',
  'Brazil': 'South America',
  'Canada': 'North America',
  'Chile': 'South America',
  'China': 'Asia',
  'Colombia': 'South America',
  'Denmark': 'Europe',
  'Egypt': 'Africa',
  'France': 'Europe',
  'Germany': 'Europe',
  'Greece': 'Europe',
  'India': 'Asia',
  'Ireland': 'Europe',
  'Italy': 'Europe',
  'Japan': 'Asia',
  'Kenya': 'Africa',
  'Malaysia': 'Asia',
  'Mexico': 'North America',
  'Netherlands': 'Europe',
  'New Zealand': 'Australia',
  'Nigeria': 'Africa',
  'Peru': 'South America',
  'Singapore': 'Asia',
  'South Africa': 'Africa',
  'South Korea': 'Asia',
  'Spain': 'Europe',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'Taiwan': 'Asia',
  'Thailand': 'Asia',
  'Turkey': 'Europe',
  'UAE': 'Asia',
  'UK': 'Europe',
  'USA': 'North America',
  'Vietnam': 'Asia',
};

export const TIERED_ACHIEVEMENTS: TieredAchievement[] = [
  {
    id: 'total_flights',
    title: 'Total Flights',
    description: 'Awarded for the total number of flights logged.',
    icon: PaperAirplaneIcon,
    getValue: (stats) => stats.totalFlights,
    formatValue: (value) => value.toLocaleString(),
    formatUnit: (value) => value === 1 ? 'flight' : 'flights',
    tiers: [
      { level: 1, name: 'Bronze', title: 'Novice Flyer', description: 'Log 10 flights.', threshold: 10 },
      { level: 2, name: 'Silver', title: 'Frequent Flyer', description: 'Log 25 flights.', threshold: 25 },
      { level: 3, name: 'Gold', title: 'Seasoned Skyfarer', description: 'Log 50 flights.', threshold: 50 },
      { level: 4, name: 'Platinum', title: 'Aviation Veteran', description: 'Log 100 flights.', threshold: 100 },
    ],
  },
  {
    id: 'longest_flight',
    title: 'Longest Flight',
    description: 'Achieve new records for a single flight distance.',
    icon: RouteIcon,
    getValue: (stats, flights) => Math.max(0, ...flights.map(f => f.distanceMiles)),
    formatValue: (value) => value.toLocaleString(),
    formatUnit: () => 'mi',
    tiers: [
      { level: 1, name: 'Bronze', title: 'The Trekker', description: 'Complete a flight over 2,000 miles.', threshold: 2000 },
      { level: 2, name: 'Silver', title: 'The Long Haul', description: 'Complete a flight over 4,000 miles.', threshold: 4000 },
      { level: 3, name: 'Gold', title: 'Endurance Flyer', description: 'Complete a flight over 6,000 miles.', threshold: 6000 },
      { level: 4, name: 'Platinum', title: 'Odyssey Flight', description: 'Complete a flight over 8,000 miles.', threshold: 8000 },
    ],
  },
  {
    id: 'unique_airports',
    title: 'Unique Airports',
    description: 'Visit a number of different airports across your travels.',
    icon: AirportIcon,
    getValue: (stats, flights) => new Set(flights.flatMap(f => [f.origin, f.destination])).size,
    formatValue: (value) => value.toLocaleString(),
    formatUnit: (value) => value === 1 ? 'airport' : 'airports',
    tiers: [
      { level: 1, name: 'Bronze', title: 'Airport Hopper', description: 'Visit 15 different airports.', threshold: 15 },
      { level: 2, name: 'Silver', title: 'Terminal Tourist', description: 'Visit 30 different airports.', threshold: 30 },
      { level: 3, name: 'Gold', title: 'Runway Roamer', description: 'Visit 50 different airports.', threshold: 50 },
      { level: 4, name: 'Platinum', title: 'Concourse Collector', description: 'Visit 75 different airports.', threshold: 75 },
    ],
  },
  {
    id: 'flight_type_master',
    title: 'Flight Type Master',
    description: 'Fly in premium classes to master the skies.',
    icon: SeatIcon,
    getValue: (stats, flights) => flights.filter(f => f.ticketClass === 'Business' || f.ticketClass === 'First').length,
    formatValue: (value) => value.toLocaleString(),
    formatUnit: () => 'Biz/First',
    tiers: [
      { level: 1, name: 'Bronze', title: 'Business Traveler', description: 'Fly once in Business or First Class.', threshold: 1 },
      { level: 2, name: 'Silver', title: 'Business Pro', description: 'Fly 5 times in Business or First Class.', threshold: 5 },
      { level: 3, name: 'Gold', title: 'Corporate Jetsetter', description: 'Fly 10 times in Business or First Class.', threshold: 10 },
      { level: 4, name: 'Platinum', title: 'Elite Suite', description: 'Fly 20 times in Business or First Class.', threshold: 20 },
    ],
  },
  {
    id: 'airline_loyalty',
    title: 'Loyalty Ace',
    description: 'Show your loyalty by flying frequently with a single airline.',
    icon: TrophyIcon,
    getValue: (stats, flights) => {
      if (flights.length === 0) return 0;
      const airlineCounts = flights.reduce((acc, flight) => {
        if (flight.airline && flight.airline !== 'Unknown Airline') {
          acc[flight.airline] = (acc[flight.airline] || 0) + 1;
        }
        return acc;
      }, {} as Record<string, number>);
      return Object.values(airlineCounts).length > 0 ? Math.max(...Object.values(airlineCounts)) : 0;
    },
    formatValue: (value) => value.toLocaleString(),
    formatUnit: (value) => value === 1 ? 'flight' : 'flights',
    tiers: [
      { level: 1, name: 'Bronze', title: 'Brand Follower', description: 'Fly 5 times with one airline.', threshold: 5 },
      { level: 2, name: 'Silver', title: 'Loyal Traveler', description: 'Fly 10 times with one airline.', threshold: 10 },
      { level: 3, name: 'Gold', title: 'Airline Advocate', description: 'Fly 20 times with one airline.', threshold: 20 },
      { level: 4, name: 'Platinum', title: 'Devoted Patron', description: 'Fly 50 times with one airline.', threshold: 50 },
    ],
  },
  {
    id: 'continental_connector',
    title: 'Continental Connector',
    description: 'Expand your horizons by visiting airports across different continents.',
    icon: GlobeAltIcon,
    getValue: (stats, flights) => {
      const visitedContinents = new Set<string>();
      flights.forEach(flight => {
        const originCountry = AIRPORT_COORDS[flight.origin]?.country;
        const destCountry = AIRPORT_COORDS[flight.destination]?.country;
        if (originCountry && COUNTRY_TO_CONTINENT[originCountry]) {
          visitedContinents.add(COUNTRY_TO_CONTINENT[originCountry]);
        }
        if (destCountry && COUNTRY_TO_CONTINENT[destCountry]) {
          visitedContinents.add(COUNTRY_TO_CONTINENT[destCountry]);
        }
      });
      return visitedContinents.size;
    },
    formatValue: (value) => value.toLocaleString(),
    formatUnit: (value) => value === 1 ? 'continent' : 'continents',
    tiers: [
      { level: 1, name: 'Bronze', title: 'Hemisphere Hopper', description: 'Visit 2 continents.', threshold: 2 },
      { level: 2, name: 'Silver', title: 'World Wanderer', description: 'Visit 3 continents.', threshold: 3 },
      { level: 3, name: 'Gold', title: 'Globe Trotter', description: 'Visit 4 continents.', threshold: 4 },
      { level: 4, name: 'Platinum', title: 'Pangaea Voyager', description: 'Visit 6 continents.', threshold: 6 },
    ],
  },
];